spring:
  application:
    name: fleet-saas
    
  # Cấu hình DataSource kết nối tới Postgres trong Docker
  datasource:
    url: jdbc:postgresql://localhost:5432/fleet_db
    username: root
    password: rootpassword
    driver-class-name: org.postgresql.Driver
    
  # Cấu hình Redis
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    com.fleet: DEBUG # Hiện log để dễ debug lúc test